export const INITIAL_PROVIDERS = [
  {
    rss: 'https://www.judicialwatch.org/feed/',
    url: 'https://www.judicialwatch.org/',
    name: 'Judicial Watch',
    logo: 'judicial-watch.svg',
    thumbnail: 'judicial-watch.png',
    slug: 'judicial-watch',
  },
  {
    rss: 'https://www.newsmax.com/rss/freedomsquarefeed/',
    url: 'https://www.newsmax.com/',
    name: 'NewsMax',
    logo: 'newsmax.svg',
    thumbnail: 'newsmax.png',
    slug: 'newsmax',
  },
  {
    rss: 'https://thenationalpulse.com/feed/',
    url: 'https://thenationalpulse.com/',
    name: 'The National Pulse',
    logo: 'national-pulse.svg',
    thumbnail: 'national-pulse.png',
    slug: 'the-national-pulse',
  },
  {
    rss: 'https://thefederalist.com/feed/',
    url: 'https://thefederalist.com/',
    name: 'The Federalist',
    logo: 'the-federalist.svg',
    thumbnail: null,
    slug: 'the-federalist',
  },
  {
    rss: 'https://www.theepochtimes.com/feed',
    url: 'https://www.theepochtimes.com/',
    name: 'The Epoch Times',
    logo: 'the-epoch-times.svg',
    thumbnail: 'the-epoch-times.png',
    slug: 'the-epoch-times',
  },
  {
    rss: 'https://feeds.a.dj.com/rss/RSSWorldNews.xml',
    url: 'https://www.wsj.com/news/opinion',
    name: 'WSJ',
    logo: 'wsj.svg',
    thumbnail: 'wsj.png',
    slug: 'wsj',
  },
  {
    rss: 'https://www.thethinkingconservative.com/feed/',
    url: 'https://www.thethinkingconservative.com/',
    name: 'The Thinking Conservative',
    logo: 'the-thinking-conservative.svg',
    thumbnail: 'the-thinking-conservative.png',
    slug: 'the-thinking-conservative',
  },
  {
    rss: 'https://freedomfirstnetwork.com/feed',
    url: 'https://freedomfirstnetwork.com/',
    name: 'Freedom First Network',
    logo: 'freedom-first-network.svg',
    thumbnail: 'freedom-first-network.png',
    slug: 'freedom-first-network',
  },
  {
    rss: 'https://twitchy.com/feed/',
    url: 'https://twitchy.com/',
    name: 'Twitchy',
    logo: 'twitchy.svg',
    thumbnail: 'twitchy.png',
    slug: 'twitchy',
  },
  {
    rss: 'https://citizenfreepress.com/feed/',
    url: 'https://citizenfreepress.com/',
    name: 'Citizen Free Press',
    logo: 'citizen-free-press.svg',
    thumbnail: null,
    slug: 'citizen-free-press',
  },
  {
    rss: 'https://hotair.com/feed',
    url: 'https://hotair.com/',
    name: 'Hotair',
    logo: 'hotair.svg',
    thumbnail: 'hotair.png',
    slug: 'hotair',
  },
  {
    rss: 'http://feeds.feedburner.com/realclearpolitics/qlMj',
    url: 'http://realclearpolitics.com',
    name: 'Real Clear Politics',
    logo: 'real-clear-politics.svg',
    thumbnail: 'real-clear-politics.png',
    slug: 'real-clear-politics',
  },
  {
    rss: 'https://www.oann.com/feed/',
    url: 'https://www.oann.com/',
    name: 'Oann',
    logo: 'one-america-news.svg',
    thumbnail: 'oann.png',
    slug: 'oann',
  },
  {
    rss: 'https://saraacarter.com/feed/',
    url: 'https://saraacarter.com/',
    name: 'Sara Carter',
    logo: 'sara-carter.svg',
    thumbnail: 'sara-carter.png',
    slug: 'saraa-carter',
  },
  {
    rss: 'https://pjmedia.com/feed/',
    url: 'https://pjmedia.com/',
    name: 'PJ Media',
    logo: 'pj-media.svg',
    thumbnail: 'pj-media.png',
    slug: 'pj-media',
  },
  {
    rss: 'https://www.theblaze.com/feeds/feed.rss',
    url: 'https://www.theblaze.com/',
    name: 'The Blaze',
    logo: 'blaze-media.svg',
    thumbnail: 'blaze.png',
    slug: 'the-blaze',
  },
  {
    rss: 'https://patriotpost.us/feed.atom',
    url: 'https://patriotpost.us',
    name: 'Patriot Post',
    logo: 'patriot-post.svg',
    thumbnail: 'patriot-post.png',
    slug: 'patriot-post',
  },
  {
    rss: 'https://www.thegatewaypundit.com/feed/',
    url: 'https://www.thegatewaypundit.com/',
    name: 'The Gateway Pundit',
    logo: 'gateway-pundit.svg',
    thumbnail: 'gateway-pundit.png',
    slug: 'the-gateway-pundit',
  },
  {
    rss: 'https://www.conservativedailynews.com/feed/',
    url: 'https://www.conservativedailynews.com/',
    name: 'Conservative Daily News',
    logo: 'conservative-daily-news.svg',
    thumbnail: 'conservative-daily-news.png',
    slug: 'conservative-daily-news',
  },
  {
    rss: 'https://townhall.com/rss/blog/main',
    url: 'https://townhall.com/',
    name: 'Town Hall',
    logo: 'townhall.svg',
    thumbnail: 'townhall.png',
    slug: 'town-hall',
  },
  {
    rss: 'https://reason.com/rss/',
    url: 'https://reason.com/',
    name: 'Reason',
    logo: 'reason.svg',
    thumbnail: 'reason.png',
    slug: 'reason',
  },
  {
    rss: 'https://www.westernjournal.com/feed/',
    url: 'https://www.westernjournal.com/',
    name: 'Western Journal',
    logo: 'western-journal.svg',
    thumbnail: 'western-journal.png',
    slug: 'western-journal',
  },
  {
    rss: 'https://theconservativetreehouse.com/feed/',
    url: 'https://theconservativetreehouse.com/',
    name: 'The Conservative Treehouse',
    logo: 'the-conservative-treehouse.svg',
    thumbnail: 'the-conservative-treehouse.png',
    slug: 'the-conservative-treehouse',
  },
  {
    rss: 'https://dailycaller.com/feed/',
    url: 'https://dailycaller.com/',
    name: 'Dailycaller',
    logo: 'daily-caller.svg',
    thumbnail: 'daily-caller.png',
    slug: 'dailycaller',
  },
  {
    rss: 'https://legalinsurrection.com/feed/',
    url: 'https://legalinsurrection.com/',
    name: 'Legal Insurrection',
    logo: 'lif.svg',
    thumbnail: 'legal-insurrection.png',
    slug: 'legal-insurrection',
  },
  {
    rss: 'http://feeds.feedburner.com/breitbart',
    url: 'https://www.breitbart.com/',
    name: 'Breitbart',
    logo: 'breitbart.svg',
    thumbnail: 'breitbart.png',
    slug: 'breitbart',
  },
  {
    rss: 'https://nationalfile.com/feed/',
    url: 'https://nationalfile.com/',
    name: 'Nationalfile',
    logo: 'national-file.svg',
    thumbnail: 'national-file.jpeg',
    slug: 'nationalfile',
  },
  {
    rss: 'https://spectator.org/feed/',
    url: 'https://spectator.org/',
    name: 'Spectator',
    logo: 'spectator.svg',
    thumbnail: 'spectator.png',
    slug: 'spectator',
  },
  {
    rss: 'https://thepoliticalinsider.com/feed/',
    url: 'https://thepoliticalinsider.com/',
    name: 'The Political Insider',
    logo: 'the-political-insider.svg',
    thumbnail: 'political-insider.png',
    slug: 'the-political-insider',
  },
  {
    rss: 'https://redstate.com/feed/',
    url: 'https://redstate.com/',
    name: 'RedState',
    logo: 'redstate.svg',
    thumbnail: null,
    slug: 'redstate',
  },
  {
    rss: 'https://www.dailywire.com/feeds/rss.xml',
    url: 'https://dailywire.com/',
    name: 'Daily Wire',
    logo: 'daily-wire.svg',
    thumbnail: null,
    slug: 'dailywire',
  },
  {
    rss: 'https://justthenews.com/rss.xml',
    url: 'https://justthenews.com/',
    name: 'Just the News',
    logo: 'justthenews.svg',
    thumbnail: null,
    slug: 'justthenews',
  },
  // {
  // Missing
  //   rss: '',
  //   url: 'https://www.stripes.com/',
  //   name: 'Stars and Stripes',
  //   logo: 'stars-and-stripes.svg',
  //   thumbnail: 'stars-and-stripes.png',
  //   slug: 'starsandstripes',
  // },
  {
    rss: 'https://www.washingtontimes.com/rss/headlines/news/',
    url: 'https://www.washingtontimes.com/',
    name: 'Washington Times',
    logo: 'washington-times.svg',
    thumbnail: null,
    slug: 'washingtontimes',
  },
];
